---
driver:
  # using docker to test
  name: ec2

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list of ansible galaxy requirements from the roles meta/main.yml
  requirements_path: dependencies.yml

platforms:
- name: centos-7

suites:
  # suites found at /test/integration/$test-name
  - name: default

transport:
  connection_timeout: 10
  connection_retries: 5
  max_ssh_sessions: 1
