---
# tasks file for cockroachdb

- name: Create the cockroach user
  user:
      name: cockroach
      create_home: yes
      home: /opt/cockroach

- name: Create the cockroach group
  group:
      name: cockroach

- name: Reset the permissions on the home directory
  file:
      name: /opt/cockroach
      mode: 0755

- name: Download and extract the binary
  unarchive:
    src: "https://binaries.cockroachdb.com/cockroach-v{{ cockroach_db_version }}.linux-{{ cockroach_db_arch }}.tgz"
    dest: /opt/cockroach
    remote_src: yes

- name: Create the bin directory
  file:
      name: /opt/cockroach/bin
      state: directory
      owner: cockroach
      group: cockroach
      mode: 0755

- name: Copy the binary into the bin directory
  copy:
      remote_src: yes
      src: "/opt/cockroach/cockroach-v{{ cockroach_db_version }}.linux-{{ cockroach_db_arch }}/cockroach"
      dest: /opt/cockroach/bin/cockroach
      owner: cockroach
      mode: 0755

- name: Copy the service definition file
  template:
      src: cockroach.service
      dest: /etc/systemd/system/cockroach.service
      mode: 0664

- name: Ensure that the service is enabled and running
  systemd:
      name: cockroach
      state: started
      daemon_reload: yes
      enabled: yes
