---
# tasks file for cockroachdb

- name: Create the cockroach user
  user:
      name: cockroach
      create_home: no
      shell: /bin/false

- name: Create the cockroach group
  group:
      name: cockroach

- name: Create cockroachDB directories
  file:
    name: "{{ item }}"
    owner: cockroach
    group: cockroach
    mode: 0755
  loop:
    - "{{ cockroach_db_path }}"
    - "{{ cockroach_db_path }}/bin"

- name: Download and extract the binary
  unarchive:
    src: "https://binaries.cockroachdb.com/cockroach-v{{ cockroach_db_version }}.linux-{{ cockroach_db_arch }}.tgz"
    dest: "{{ cockroach_db_path }}"
    remote_src: yes

- name: Copy the binary into the bin directory
  copy:
      remote_src: yes
      src: "{{ cockroach_db_path }}/cockroach-v{{ cockroach_db_version }}.linux-{{ cockroach_db_arch }}/cockroach"
      dest: "{{ cockroach_db_path }}/bin/cockroach"
      owner: cockroach
      mode: 0755

- name: Copy the service definition file
  template:
      src: cockroach.service
      dest: /etc/systemd/system/cockroach.service
      mode: 0664
  notify:
    - reload service

- name: Ensure that the service is enabled and running
  systemd:
      name: cockroach
      state: started
      daemon_reload: yes
      enabled: yes
